credentials:
  usernames:
    rglicket:
      email: rglickert@me.com
      name: Bobby
      password: misterwhisper-admin # To be replaced with hashed password
    m-ali-awan:
      email: muhammad.edtech@gmail.com
      name: Muhammad
      password: misterwhisper-dev # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: misterwhisper-custom-chatbot
preauthorized:
  emails:
  - muhammad.edtech@gmail.com